---
- hosts: all
  become: true

  tasks:
    - name: Install security updates
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - openssl
        - openssh
      ignore_errors: yes 
    - name: Verify if Docker is installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes    
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: 
        output.failed